### ISSUE TITLE
WearHacks!

### ISSUE THREAD

**Issue by makrandgupta** [Hackalist/Hackalist.github.io#106]
Hey guys, 

we have a bunch of hackathons coming up for this year. All information is available here: wearhacks.com

Wanted to add them here. 

Cheers!

**Comment by KevinPayravi** [comment]
Working on it!

**Comment by KevinPayravi** [comment]
I added WearHacks through May (minus Boston; it appears to be mis-labelled as May 1-31st?)

- https://github.com/Hackalist/Hackalist.github.io/commit/f898736253d387d30dc9114e49e12c931481aff0
- https://github.com/Hackalist/Hackalist.github.io/commit/279e6e7d59c5200817d0dd6261a7f74560a9c450

If you know of any details we can fill in, feel free to comment or make a pull request.

**Comment by paked** [comment]
It looks like we can close this. Feel free to re-open if more needs to be done.

Thanks!

**Comment by makrandgupta** [comment]
Thanks guys! I will re-open this when we have more events confirmed

**Comment by makrandgupta** [comment]
Just adding some more information:
We do not offer Travel re-imbursements for any hackathon
We love highschoolers <3

WearHacks Tunis shows up as Wearhacks Rome.

**Comment by KevinPayravi** [comment]
Working...

**Comment by KevinPayravi** [comment]
@makrandgupta Updated and fixed.

- https://github.com/Hackalist/Hackalist.github.io/commit/7cb1394d17f92f07bb8483c85d296b6c4ab62823
- https://github.com/Hackalist/Hackalist.github.io/commit/52e3a6357aa5d6edcbe00a18c5ae22d07080bb6c
- https://github.com/Hackalist/Hackalist.github.io/commit/e76dbd26ff8499f6641366ab35963e45e4579aaa

Thank you!

**Comment by makrandgupta** [comment]
Thanks @KevinPayravi!
