### ISSUE TITLE
What to put in 2.0 / Getting community input

### ISSUE THREAD

**Issue by paked** [Hackalist/Hackalist.github.io#122]
I think it would be really great to get some community opinion about what we should do for V2.0.

If everyone is fine with it, I'll post this message into HH:

```
Yo Hackathon Hackers.

http://hackalist.org is getting an upgrade. Are there any features you would like to see added for version 2.0?

Currently we are:
- Redesigning the frontend
- Improving the API usability

Thanks,
Kevin Payravi, Rodrigo Argumedo and I.
```

Is there anything else we want to say?

cc:// @rodrigoargumedo @KevinPayravi

**Comment by rodrigoargumedo** [comment]
@paked I think this is pretty good letter to start off. **Off to the presses!** @KevinPayravi

**Comment by paked** [comment]
I'll send this once @KevinPayravi approves :)

**Comment by KevinPayravi** [comment]
Want to throw in a bullet for us adding in cost as a field?

Otherwise, looks good! Thanks guys :)

**Comment by paked** [comment]
OK. Posted to HH:

https://www.facebook.com/groups/hackathonhackers/permalink/1204483016273848/

**Comment by KevinPayravi** [comment]
Two more fields I thought about adding:

- MLH (yes/no)
- Buses (yes/no)

Thoughts?

**Comment by paked** [comment]
:+1: for MLH

Not quite sure why we need buses :/

**Comment by rodrigoargumedo** [comment]
:+1: for MLH eligibility.

**Comment by KevinPayravi** [comment]
Nice, MLH sounds good to go then!

My thought process on buses is that I often see hackathons that don't offer travel reimbursements, but do send buses to neighboring schools. I think it's valuable information, but at the same time, it's typically only valuable to students from the school's surrounding area.

**Comment by paked** [comment]
I think we could just put that kind of thing in notes.

**Comment by kevkevinpal** [comment]
you might want to mention if you have to pay to get into the hackathon

**Comment by KevinPayravi** [comment]
@kevkevinpal Thanks for the feedback! We're currently putting that in the notes (if we missed one, please let us know); we're also planning on putting in cost as a separate field soon (see https://github.com/Hackalist/Hackalist.github.io/issues/83)

**Comment by veronicasyseo** [comment]
International travel reimbursement vs domestic (NA/USA specific) travel reimbursement
Distance and budget/flight calculator by integrating APIs?

**Comment by rodrigoargumedo** [comment]
This will make an huge impact to us greatly to inplement this but from what I understand based on the question, I would assume that:

1. the browser would prompt the user ro request to HTTP GET location from where they are and
2. Route the requested location and perform a Google search API with an array of prices of the flights.

@kevinpayravi @paked How does this sound to you? Is it good? Bad?
