### ISSUE TITLE
'Add to Calendar' button

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#123]
Not a priority, but having an "Add to Calendar" button for each hackathon would be a nice feature. Any disagreement, please say so!

Could be a part of 2.0, but could be added later on.

**Comment by rodrigoargumedo** [comment]
Totally in favor of it! :+1:

**Comment by paked** [comment]
@KevinPayravi This is awesome! Do we have any ideas how it would work?

**Comment by KevinPayravi** [comment]
Shouldn't be difficult. I believe for Google Calendar (and probably others), it involves simply creating a URL with fields filled out (name, time, location, etc.), and once clicked, it directs the user to add it to their Google Calendar.

**Comment by rodrigoargumedo** [comment]
The hardest part is when you try to export the event details on a iCal format?

**Comment by goatandsheep** [comment]
Use the http://addtocalendar.com/ plugin

**Comment by Mymoza** [comment]
I took a look at the plugin suggested by @goatandsheep and we would need to add these info to the JSON : 

* Start time 
* End time 
* TimeZone 

works well though :)

**Comment by adeora7** [comment]
@KevinPayravi Can I make these changes if you are planning to include it ?

**Comment by rodrigoargumedo** [comment]
Just fork it and feel free to open a pull request when you are ready to push those changes into the master branch.

Sent from my iPhone

On Jan 3, 2017, at 6:25 AM, Abhishek Deora <notifications@github.com<mailto:notifications@github.com>> wrote:


@KevinPayravi<https://github.com/KevinPayravi> Can I make these changes if you are planning to include it ?

-

**Comment by adeora7** [comment]
@rodrigoargumedo 
I wrote the code for the same. Now I would like to discuss two things before creating a pull request.
1. Time zone is mandatory but if start/end time are not given should we still give the "add to calendar button".
2. Instead of changing the JSON format as mentioned by @Mymoza , I made changes in app.js although I had to add three new properties for time zone, start time and end time.

**Comment by paked** [comment]
Just a thought here: What point is having an 'Add to Calendar' button for a hackathon which you have not even been accepted into yet?

This might make sense for online events, but something like PennApps where there is a reasonably high rejection rate (#topical) just doesn't seem right. Heck, it might even confuse some people into thinking they can just rock up!

**Comment by KevinPayravi** [comment]
Thanks for writing the code for it @adeora7! 

Good point @paked...I could maybe see it being useful for someone who wants to list hackathons their interested in on their personal calendars for easy reference, but I imagine that's a very small portion of the population. Any other thoughts? Otherwise, I'd be in favor of dropping the idea of having the button (not to disregard your work, @adeora7?)

**Comment by goatandsheep** [comment]
@KevinPayravi the only use case I can think of is if someone wanted a calendar of all the events for people to go to, but we could just manually do one ourselves without the add to calendar button
