### ISSUE TITLE
Twitter presence

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#125]
Something I've had on my mind but never got to is an official Hackalist Twitter account. It'd basically be used to tweet out general hackathon updates (when we add a new hackathon / when a hackathon is coming up / etc.), along with allowing others to tweet at us updates for the site.

Unfortunately [@hackalist](@hackalist) was taken back in 2009. Twitter does have a policy of removing accounts inactive for more than 6 months, but they don't seem to actually do so - and there is no way to officially acquire another person's account, even if inactive, unless you can prove trademark infringement or impersonation. Short of me filing a trademark, I think we're out of luck. I tweeted at the account, so hopefully they respond. But if nothing comes of that...

...I've reserved [@hackalistorg](https://twitter.com/hackalistorg) as our account. Once we're up and running, I'll give our collaborators access (probably through TweetDeck). If anyone has any suggestions for a better username too, feel free to comment! Thanks.

**Comment by rodrigoargumedo** [comment]
That is a great idea! I am working on something like this in another app with hapi.js. So, this is my next challenge in my [Todoist](https://todoist.com) task now and maybe setting a 24-48 hour deadline when I have enough experience with it. I may rewrite the entire app with the framework with the API restructured.

You can feel free to learn more and weigh in on this change with [hapi.js](https://hapijs.com).

Giving us the TweetDeck access is the same as Twitter usernames. I've used and done this before.

**Comment by rodrigoargumedo** [comment]
Also, I should be able to track down the presence by recent tweets.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo could you expand on what you're doing with Hapi? What I originally meant was simply having a Twitter account we'd manually tweet from (sorry if it wasn't clear), but I'm curious what you're thinking of doing.

**Comment by rodrigoargumedo** [comment]
Oh, sorry. I wasn't thinking clearly. It was like 3am when i saw it and misread the issue.Oops. :disappointed: 

That aside, I think @hackalistorg should be a good name to put in. How about you, @paked?

**Comment by paked** [comment]
Works for me!

**Comment by KevinPayravi** [comment]
Started tweeting, followed a few dozen hackathons. Going to tweet a bit to establish the account before following more accounts and sharing the feed with Hackathon Hackers et. al.

I'll get you guys TweetDeck Access soon :)
