### ISSUE TITLE
Add REimagine Waste Hackathon in Bangalore, India

### ISSUE THREAD

**Issue by twodustyfeet** [Hackalist/Hackalist.github.io#126]
Urban waste in India is a problem that is looms larger every year. Poor waste pickers dig through our scraps trying to make a living from whatever plastics and metals we have left for them to resell. NGOs are trying to improve waste pickers' conditions, but they are fighting a one-sided battle. Indians around the country are demanding more reliable, ecologically safe waste services to clean up their cities. This movement needs the combined efforts of programmers, designers, innovators and entrepreneurs to rethink waste and incorporate waste pickers into the future of clean and liveable cities for India.

Join here: http://www.reimaginewaste.in/

**Comment by KevinPayravi** [comment]
Working!

**Comment by KevinPayravi** [comment]
Added with the following commits:

- https://github.com/Hackalist/Hackalist.github.io/commit/0ecbd459d3572c11f7d23e60db3cc55fa7ce56a4
- https://github.com/Hackalist/Hackalist.github.io/commit/784bb9d4705efc606b393ac641e6010bb8736bce
- https://github.com/Hackalist/Hackalist.github.io/commit/cd7ff39e8ab0f42eaf361e19d0ffb6cd8a23c290

Thanks @twodustyfeet!

**Comment by KevinPayravi** [comment]
Also updated with confirmation of prizes.

@twodustyfeet We're missing details on the expected number of participants, whether travel reimbursements are offered, and whether high schoolers can attend. If you know any of these details, please feel free to comment with them. Thanks!

**Comment by twodustyfeet** [comment]
@KevinPayravi Expected participants is >100. No travel reimbursements. Yes high schoolers can attend. Many thanks!!

**Comment by KevinPayravi** [comment]
@twodustyfeet Updated, thank you!
