### ISSUE TITLE
Add logo url field

### ISSUE THREAD

**Issue by AdamMc331** [Hackalist/Hackalist.github.io#146]
In order for a really smooth mobile app on this, it would be awesome to include the hackathon's logo on a detailed screen. Can we add a new field for this in the JSON of each entry?

May take some time to update the current entries, though.

**Comment by KevinPayravi** [comment]
Solid idea. I'm up for including it alongside our new 'cost' field.

**Comment by AdamMc331** [comment]
Why are you adding a cost field?

**Comment by KevinPayravi** [comment]
@AdamMc331 Take a look at https://github.com/Hackalist/Hackalist.github.io/issues/83

We definitely don't have to include it - if you have thoughts on it, feel free to add to the issue. A vast majority of the hackathons we list are free, but a small number have a cost associated.

**Comment by AdamMc331** [comment]
That's understandable. While we're adding fields, I thought earlier it would be cool to add a "mlhMemberEvent" field that could also be "yes|no|unknown" (unknown being in progress or something).
