### ISSUE TITLE
Please add Hack Homelessness 

### ISSUE THREAD

**Issue by squigglydonut** [Hackalist/Hackalist.github.io#147]
Hack Homelessness
September 23-25
The Tech Museum, San Jose CA
hackhomelessness.com

I'm the organizer. I'm not sure if I need to open up an issue or what the process is for adding so let me know if i need to do something different or you need more info. Thanks a bunch for setting this up it's really cool!

**Comment by KevinPayravi** [comment]
@squigglydonut Thanks for your submission! I've added Hack Homelessness :)

I put 'unknown' for whether or not prizes are provided; as soon as you have more details on it, feel free to comment here! If you also have a Facebook, Twitter, or Google+ you'd like us to link to, feel free to link us.

Good luck with the event!

**Comment by squigglydonut** [comment]
Thank you and thanks for supporting the hackathon community in this way!
ᐧ


Zach Moore
330-285-0126
