### ISSUE TITLE
Adding MLH field

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#151]
From previous discussions (most recently https://github.com/Hackalist/Hackalist.github.io/issues/146), we'd like to implement an MLH boolean field for whether or not a hackathon is an MLH member.

`MLH` or `mlhMemberEvent`
`yes` | `no` | `unknown`

Any MLH events can have a little MLH icon placed somewhere within their listing.

**Comment by rodrigoargumedo** [comment]
Revisiting this issue,. Are we still going to implement this at all?

**Comment by bencooper222** [comment]
So will this be implemented?

**Comment by mathu97** [comment]
Any update on this issue?

**Comment by bencooper222** [comment]
No one has worked on this code for a while...

**Comment by rodrigoargumedo** [comment]
Hello guys,

Thank you for the continued support. We've been busy for the past couple months and we, as the team, hadn't had the time to sit down and discus this issue. Hopefully we can implement this feature soon.

**Comment by aarohmankad** [comment]
Hey there, I'm an old contributor to the repo, and I'd be happy to build the functionality if time is an issue!

**Comment by rodrigoargumedo** [comment]
@aarohmankad Go for it! You are more than welcome to bring in a pull request that does this so that I can close this issue later.
