### ISSUE TITLE
Add missing hackathons entries

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#163]
There are hundreds of hackathons out there, and we want them listed on Hackalist! This is an everlasting issue.

To contribute:
- Find a hackathon you would like to add! Our listed hackathons shouldn't be geographically restricted (e.g. a hackathon in London should be open to people from anywhere, not just London).
- Hackalist's data is stored in JSON (JavaScript Object Notation) files, organized by year and month.
- Check out our [README](https://github.com/Hackalist/Hackalist.github.io/blob/master/README.md) and take a look at the information on our API.
- Go into [our API](https://github.com/Hackalist/Hackalist.github.io/tree/master/api/1.0) and navigate to the year/month you would like to add a hackathon into.
- Add a JSON object for your hackathon (tip: look at how previous listings are done to see how yours should look).
- Check for errors in the JSON file with [JSONLint](http://jsonlint.com/).
- Good to go? Submit your pull request!

**Comment by paked** [comment]
Suggestion for anyone who wants to add new hackathons:

- MLH NA: https://mlh.io/seasons/na-2017/events
- MLH EU: https://mlh.io/seasons/eu-2017/events

We don't currently have a way of automatically adding in MLH events. For now, it's a great way to get your PR counter up... But it *would* be wonderful if someone could come up with a script to automate it.

**Comment by KevinPayravi** [comment]
Closing as Hacktoberfest is over.

**Comment by KevinPayravi** [comment]
Reopened for 2017!
