### ISSUE TITLE
Clicks/Views on hackathon

### ISSUE THREAD

**Issue by adeora7** [Hackalist/Hackalist.github.io#235]
How many times a hackathon was visited using this platform can be displayed. It can be displayed publicly or informed through emails monthly or weekly to the concerned people

**Comment by paked** [comment]
@adeora7: How do you propose we collect this data?

**Comment by adeora7** [comment]
@paked 

1. According to a few post which i read, google analytics can be used to keep a track clicks on links. This data can then be retrieved using the google analytics API.

2. we can maintain a JSON for the same.

3. using a database to maintain data (I don't think it will be feasible here)

**Comment by KevinPayravi** [comment]
This could be a possibility by having a dedicated server (which I am happy to host) that connects to the Google Analytics API; the Hackalist site could then grab click data from that server.

The question is whether this data is useful for the website. I don't think it's particularly useful to have on the site itself...we could have a separate page that provides view data, but I don't think there is a strong demand.

**Comment by aarohmankad** [comment]
Coming from an organizer's perspective, it's always helpful to understand where our traffic is coming from. As of now, that can be assigned by making the url in the json specific to hackalist. (i.e. citrushack.com/?ref=hackalist)

**Comment by rodrigoargumedo** [comment]
@aarohmankad: I never actually thought of this but this is a great idea that I can modify in the app.js.

cc @Hackalist/maintainers What do you guys think?
