### ISSUE TITLE
Please can you add a hack out

### ISSUE THREAD

**Issue by BeateKub** [Hackalist/Hackalist.github.io#240]
This is a hack to get people interested and involved in open source solutions to travel and transport - integrating public transport and shared mobility into Mobility as a Service.

It will bring together passionate developers, digital artists, IoT experts and business savvy professionals, who are interested in the future space of 'Mobility as a Service', and want to be part of delivering this at scale, through open collaboration.

We want folk to use this weekend to catapult their ideas into reality, take a idea or concept to working prototype in 48 hours. With the support of our global open source community and onsite tech gurus, facilitated by our partners Iotic Labs.

And the difference between a Hackathon and a HackOut? This isn't a race. Its about building meaningful relationships and powerful collaborations that can get us somewhere, together.

https://www.eventbrite.co.uk/e/travelspirit-hackout-manchester-pre-registeration-tickets-27680779958

If you can add it to the list, I'd be v grateful.
Best wishes,
Beate

**Comment by paked** [comment]
@BeateKub: We usually allow CodeDay's to get put here, so I don't think that this will be an issue.

I'll leave this open for someone to take.

**Comment by KevinPayravi** [comment]
@BeateKub Done! (https://github.com/Hackalist/Hackalist.github.io/commit/15a47ec960f50d3bd5c28271c8cfddaf7fffa093).

Thank you for your contribution! We could use a few more details about the event. Does the Hackout provide travel reimbursements, prizes, and/or accept high schoolers? How many attendees are you aiming for?

**Comment by BeateKub** [comment]
Hi Kevin,

The key  prize for winners is expenses paid trip to Montreal in May, to join a global hackathon.

We can accept high schoolers, as long as they have appropriate parental consent. We are not planning to provide travel reimbursements.

Many thanks for your help
Beate

Sent from my iPhone

**Comment by KevinPayravi** [comment]
@BeateKub Updated (https://github.com/Hackalist/Hackalist.github.io/commit/55a5f8acf7920c0f1b3384e880307ac87f8fc798) - thank you!
