### ISSUE TITLE
Request to add Octane Hackathon 

### ISSUE THREAD

**Issue by Kscheven** [Hackalist/Hackalist.github.io#242]
**Global, virtual hackathon (open to anyone).** 

Open **Timeline:** January 9th, 2017 - Feburary 9th, 2017

**Website:** http://octanehack.com/

**Prizes:** Over $10K - including iPad Pros, Apple Watches, Amazon Echos

**Challenge**: Use HPE's ALM Octane API to solve one of four software development challenges.

**Comment by KevinPayravi** [comment]
Hi there - apologies for the wait! I know the event is over, so listing it on Hackalist isn't of much use, but it will at least be in our archive :)

I have added Octane Hackathon with https://github.com/Hackalist/Hackalist.github.io/commit/15a47ec960f50d3bd5c28271c8cfddaf7fffa093

I hope the event went well!
