### ISSUE TITLE
Request to add SWHacks

### ISSUE THREAD

**Issue by mcaprile** [Hackalist/Hackalist.github.io#247]
{
                  "title": "Southwest Hacks (SWHacks)",
                  "url": "http://swhacks.org",
                  "startDate": "March 10",
                  "endDate": "March 12",
                  "year": "2017",
                  "city": "Tempe, AZ, United States",
                  "host": "Arizona State University",
                  "length": "48",
                  "size": "unknown",
                  "travel": "no",
                  "prize": "yes",
                  "highSchoolers": "yes",
                  "cost": "free",
                  "facebookURL": "https://www.facebook.com/swhacksofficial/",
                  "twitterURL": "https://twitter.com/swhacksofficial",
                  "googlePlusURL": "",
                  "notes": "Must be 18+"
            },

**Comment by KevinPayravi** [comment]
Added! https://github.com/Hackalist/Hackalist.github.io/commit/1055d56b5d456aa86411684046872269e803b42f

Thanks @mcaprile
