### ISSUE TITLE
Request to add HACKATHONclt MMXVII

### ISSUE THREAD

**Issue by jamesblau** [Hackalist/Hackalist.github.io#249]
{
  "title": "HACKATHONclt MMXVII",
  "url": "http://hackathonclt.org/",
  "startDate": "March 24",
  "endDate": "March 25",
  "year": "2017",
  "city": "Charlotte, NC, United States",
  "host": "HACKATHONclt",
  "length": "24",
  "size": "500+",
  "travel": "no ",
  "prize": "yes",
  "highSchoolers": "no",
  "cost": "free",
  "facebookURL": "https://www.facebook.com/hackathonclt",
  "twitterURL": "https://twitter.com/charlottehacks",
  "instagramURL": "https://instagram.com/hackathonclt",
  "meetupURL": "https://meetup.com/hackathonclt",
  "notes": "BIG DATA hackathon, challenge related to helping Big Brother Big Sister, swag, must be 18+"
}

**Comment by KevinPayravi** [comment]
Done (https://github.com/Hackalist/Hackalist.github.io/commit/15a47ec960f50d3bd5c28271c8cfddaf7fffa093).

Thank you for your contribution!
