### ISSUE TITLE
Request to add lewHacks()

### ISSUE THREAD

**Issue by ex0dus-0x** [Hackalist/Hackalist.github.io#256]
{
"title": "lewHacks()",
"url": "http://lewhacks.com/",
"startDate": "March 5",
"endDate": "March 5",
"year": "2017",
"city": "New York, NY, United States",
"host": "Francis Lewis High School",
"length": "12",
"size": "100+",
"travel": "no ",
"prize": "yes",
"highSchoolers": "yes",
"cost": "free",
"facebookURL": "https://www.facebook.com/events/1876327812646392/",
"twitterURL": "https://twitter.com/lewhacks",
"instagramURL": "https://instagram.com/lewhacks",
"notes": "First student hackathon at Francis Lewis High School! Free and open to high school students who want to build amazing technologies!"
}

**Comment by KevinPayravi** [comment]
Done (https://github.com/Hackalist/Hackalist.github.io/commit/15a47ec960f50d3bd5c28271c8cfddaf7fffa093).

Thank you for your contribution!
