### ISSUE TITLE
Request to add Hack HSV to the list

### ISSUE THREAD

**Issue by sachin1329** [Hackalist/Hackalist.github.io#259]
Hi, my name is Sachin Katyal, the founder of Hack HSV. Hack HSV is Alabama's first high school hackathon, and I would love it if it would be added to Hackalist.  Just some information about Hack HSV. It is exclusively a high school hackathon in Huntsville, Alabama where over 100 students are able to participate. Transportation is unfortunately not provided. The competition will take place on April 15, 2017, where it is only a 12-hour hackathon. Prizes are also given out at the end of the competition. For information, you can head over to our website www.hackhsv.com.

**Comment by KevinPayravi** [comment]
Done (https://github.com/Hackalist/Hackalist.github.io/commit/15a47ec960f50d3bd5c28271c8cfddaf7fffa093).

Thank you for your contribution!
