### ISSUE TITLE
[Submission] MontyHacks NJ

### ISSUE THREAD

**Issue by julia-guo** [Hackalist/Hackalist.github.io#277]
(http://montyhacks.com/ for details)
-No travel reimbursements
-Yes prizes
-Yes high schoolers
-Yes free
Hosted by Montgomery High School
12 hours
Capacity: 200
April 22 in Skillman, New Jersey

Social media links on website.

**Comment by jrsai** [comment]
{
      "title": "MontyHacks",
      "url": "http://montyhacks.com/",
      "startDate": "April 22",
      "endDate": "April 22",
      "year": "2017",
      "city": "Skillman, New Jersey",
      "host": "Montgomery High School",
      "length": "12",
      "size": "200",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/MontyHacks/",
      "twitterURL": "https://twitter.com/MontyHacks",
      "googlePlusURL": "",
      "notes": ""
    }
