### ISSUE TITLE
[Submission] AngelHack's 10th Global Hackathon Series

### ISSUE THREAD

**Issue by hazeltrack** [Hackalist/Hackalist.github.io#282]
Hello,

Could someone add our 10th Global Series Hackathons to the list? All of the info is below, I'm just not confident about doing a pull request. Let me know what other info I can help provide! All events will have prizes, no travel stipends provided. 

Nairobi, March 23–24	http://angelhack.com/angelhack-global-hackathon-series-nairobi
Novosibirisk, April 1–2	http://angelhack.io/
Manipal, April 8–9	http://angelhack.com/angelhack-global-hackathon-series-manipal
Innopolis, April 22–23	http://angelhack.com/angelhack-global-hackathon-series-innopolis
Los Angeles, April 29–30	http://angelhack.com/angelhack-global-hackathon-series-los-angeles
Mumbai, April 29–30	http://angelhack.com/angelhack-global-hackathon-series-mumbai
Sydney, April 29–30	http://angelhack.com/angelhack-global-hackathon-series-sydney
New Delhi, May 6–7	http://angelhack.com/angelhack-global-hackathon-series-new-delhi
Melbourne, May 6–7	http://angelhack.com/angelhack-global-hackathon-series-melbourne
San Francisco, May 6–7	http://angelhack.com/angelhack-global-hackathon-series-san-francisco
Abu Dhabi, May 10–11	http://angelhack.com/angelhack-global-hackathon-series-abu-dhabi
Brisbane, May 13–14	http://angelhack.com/angelhack-global-hackathon-series-brisbane
Barcelona, May 13–14	http://angelhack.com/angelhack-global-hackathon-series-barcelona
Gaza, May 19–20	http://angelhack.com/angelhack-global-hackathon-series-gaza
Atlanta, May 20–21	http://angelhack.com/angelhack-global-hackathon-series-atlanta
Quito, May 20–21	http://angelhack.com/angelhack-global-hackathon-series-quito
Kalingrad, May 27–28	http://angelhack.io/
Bogota, May 27–28	http://angelhack.com/angelhack-global-hackathon-series-bogota
Seattle, May 27–28	http://angelhack.com/angelhack-global-hackathon-series-seattle
Saint Petersburg, June 3–4	http://angelhack.io/
Hyderabad, June 3–4	http://angelhack.com/angelhack-global-hackathon-series-hyderabad
Jaipur, June 3–4	http://angelhack.com/angelhack-global-hackathon-series-jaipur
Bangalore, June 3–4	http://angelhack.com/angelhack-global-hackathon-series-bangalore
Washington DC, June 3–4	http://angelhack.com/angelhack-global-hackathon-series-washington-dc
Sri Lanka, June 10–11	http://angelhack.com/angelhack-global-hackathon-series-sri-lanka
Manhattan, June 10–11	http://angelhack.com/angelhack-global-hackathon-series-manhattan
Singapore, June 17–18	http://angelhack.com/angelhack-global-hackathon-series-singapore
Boston, June 17–18	http://angelhack.com/angelhack-global-hackathon-series-mumbai
London, June 17–18	http://angelhack.com/angelhack-global-hackathon-series-london
Austin, July 8–9	http://angelhack.com/angelhack-global-hackathon-series-austin
Moscow, July 10–11	http://angelhack.io/
Santiago, July 15–16	http://angelhack.com/angelhack-global-hackathon-series-santiago
Silicon Valley, July 22–23	http://angelhack.com/angelhack-global-hackathon-series-silicon-valley
San Pedro Sula, July 29–30	http://angelhack.com/angelhack-global-hackathon-series-san-pedro-sula

Thank you!
Rachel

**Comment by binhonglee** [comment]
> Washington DC, June 3–4	http://angelhack.com/angelhack-global-hackathon-series-washington-dc

Link is broken.

> Boston, June 17–18	http://angelhack.com/angelhack-global-hackathon-series-mumbai

URL should be http://angelhack.com/angelhack-global-hackathon-series-boston instead.
