### ISSUE TITLE
Hacklist Submission: United We Hack 2 - Singapore 

### ISSUE THREAD

**Issue by Kscheven** [Hackalist/Hackalist.github.io#290]
[United We Hack 2.0 Website](http://unitedwehack2.com/
)
April 29-30, 2017

General Assembly, Singapore

All women and male allies welcome.

Additional Info: This April 29-30, 2017 at General Assembly, the Singapore Committee for UN Women and AngelHack are bringing back UNited We Hack. In 2017, we will look into barriers preventing female entrepreneurship, and we want you to take up the 2-day challenge! Health, Safety, Economic Empowerment, and Culture – Take your pick and hack a solution. This year we’re adding on more exciting events including a General Assembly masterclass session, and a screening of the award-winning documentary CODE: Debugging the Gender Gap.

**Comment by KevinPayravi** [comment]
Added in https://github.com/Hackalist/Hackalist.github.io/commit/55addb59f0aad3975f15ba9943facf5022a7346b

Apologies for the wait!
