### ISSUE TITLE
Hackalist Submission: West Valley College Hackathon

### ISSUE THREAD

**Issue by VaibhavBajaj** [Hackalist/Hackalist.github.io#292]
Students will be broken into teams and given a period of 6-8 hours to complete projects based on a theme provided at the event. 
The hackathon spans over 9 hours from 8:30AM to 5:30PM on May 13th.
More information about the event is given on our website: [https://wvhacks.wordpress.com/](https://wvhacks.wordpress.com/)

This is a great opportunity for students to immerse themselves into coding and meet fellow experienced programmers.

**Comment by KevinPayravi** [comment]
Added in https://github.com/Hackalist/Hackalist.github.io/commit/55addb59f0aad3975f15ba9943facf5022a7346b

Apologies for the wait!
