### ISSUE TITLE
[Submission] Add ByteHacks to List

### ISSUE THREAD

**Issue by bytehacks** [Hackalist/Hackalist.github.io#296]
Title: ByteHacks
URL: http://bytehacks.org
Start Date: June 24th, 2017
End Date: June 25th, 2017
City: New York, NY, United States
Host: Spotify HQ
Length: 24 hours
Size: 150
Travel: No
Prizes: Yes
High Schoolers Allowed: Yes
Cost: free
facebookURL: https://www.facebook.com/events/67263161958857
Notes: This is an all-women hackathon for high school and college women only.

**Comment by jrsai** [comment]
{
      "title": "ByteHacks",
      "url": "http://bytehacks.org/",
      "startDate": "June 24",
      "endDate": "June 25",
      "year": "2017",
      "city": "New York, NY",
      "host": "Spotify HQ",
      "length": "24",
      "size": "150",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/events/672631619588573/",
      "twitterURL": "",
      "googlePlusURL": "",
      "notes": "This is an all-women hackathon for high school and college women only."
    }
