### ISSUE TITLE
BBVA Open Challenge Global Trends

### ISSUE THREAD

**Issue by johhen** [Hackalist/Hackalist.github.io#325]
{
      "title": "BBVA Open Challenge Global Trends",
      "url": "https://www.centrodeinnovacionbbva.com/en/openchallenges/globaltrends",
      "startDate": "August 1",
      "endDate": "September 26",
      "year": "2017",
      "city": "Chicago",
      "host": "Next Money",
      "travel": "no",
      "prize": "yes",
      "cost": "free",
}

**Comment by johhen** [comment]
New Hackaton

**Comment by rodrigoargumedo** [comment]
@johhen Can you provide more information, if available, like: Does the event accept high schoolers? social links to the event? and any additional notes that the participants need to know?

**Comment by johhen** [comment]
Difficult to anticipate the size, the event is online and world-wide (anyone can sign up). The conditions indicates that participantes should be of "age of majority", so most high schoolers would most likely not be able to participate.

**Comment by rodrigoargumedo** [comment]
Thank you so much for the info! I appreciate it. Will update this in the next commit.

**Comment by rodrigoargumedo** [comment]
https://github.com/Hackalist/Hackalist.github.io/commit/091f3a8607051fd6640760a8c6e0043feb4fd796

all done!
