### ISSUE TITLE
Toggles not working correctly after initial selection

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#33]
Did some testing of the toggles (travel reimbursements, prizes, and high schoolers). If I toggle something, it will properly properly show only hackathons that meet that toggle.  However, clicking the toggle again to disable it will not restore the full list of hackathons (e.g. if I toggle"Accept High Schoolers", it will properly show only hackathons that accept high schoolers; when I disable the toggle, nothing changes).

**Comment by KevinPayravi** [comment]
@paked could you take a look at this? :)

**Comment by paked** [comment]
Hmm was this an issue before my merge as well? Would it be OK if I used a different toggle system?

**Comment by KevinPayravi** [comment]
It wasn't an issue before, no. If you know a better solution, feel free to
implement it!

**Comment by paked** [comment]
@KevinPayravi this can be closed, I think

**Comment by KevinPayravi** [comment]
Thanks - closing!
