### ISSUE TITLE
Can you please add Smart Energy Hackathon Prague 2017?

### ISSUE THREAD

**Issue by studenik** [Hackalist/Hackalist.github.io#343]
Name: Smart Energy Hackathon Prague 2017
Dates: 3-5 Nov 20127
Location: Prague, Czech Republic
FREE registration: www.ceehacks.com
PRIZE MONEY EUR 7 000
TRAVEL COSTS covered up to EUR 150 per person

**Comment by cravend** [comment]
I'll handle it!

**Comment by studenik** [comment]
Cheers:-)

S.V.B.E.E.Q.V.

29. 9. 2017 v 19:51, Dalton <notifications@github.com>:
