### ISSUE TITLE
AutoMobility LA’s Hackathon

### ISSUE THREAD

**Issue by JMPR-Public-Relations** [Hackalist/Hackalist.github.io#357]
Developers are invited to participate in AutoMobility LA’s Hackathon presented by Honda Innovations, which takes place over 24 hours on November 27-28 at the Los Angeles Convention Center.
Participants will have the opportunity to use data from the City of L.A. to address mobility challenges posed to a dynamic city like Los Angeles when it comes to hosting major events. Those solutions for DRIVERS or PASSENGERS could range from a navigation app for locals to avoid traffic jams, to an AR app for visitors to explore the area, to a fully blown Virtual Reality app for fans to experience the games in vehicle. We’ll provide the data, the tools, the car and the caffeine. You just need to bring your great ideas and coding skills.
Grand prize winners will be announced and awarded on the main stage of AutoMobility LA, inside the Technology Pavilion on Wednesday, November 29.
For more information, visit automobilityla.com/hackathon

**Comment by rodrigoargumedo** [comment]
Closing because #361 was merged into this issue.
