### ISSUE TITLE
Help Needed : Adding a Hackathon ! 

### ISSUE THREAD

**Issue by resheilA** [Hackalist/Hackalist.github.io#359]
Hello,
Can you please add out hackathon.

Hosted by HackInfinity for 28 hours
Capacity: 180
Cost: Free
Note: India’s biggest student hackathon in India.  Also the first hackathon to provide pre-incubation to students.

Travel reimbursement offered! 
Prizes offered! 
High schoolers accepted!

**Comment by arc113** [comment]
do you mean InOut? If yes, It is already there..

**Comment by resheilA** [comment]
No we have a different hackathon in India named Hack Infinity ! Check out our website hackdaiict.in

**Comment by KevinPayravi** [comment]
Completed by @noramyer

https://github.com/Hackalist/Hackalist.github.io/pull/360
