### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by paked** [Hackalist/Hackalist.github.io#36]
[I just noticed that we don't have a license... I suggest you do so.](https://help.github.com/articles/open-source-licensing/)

**Comment by KevinPayravi** [comment]
Ah, yea, this is something I wish I had done at the beginning. Problem is that other users have already contributed to the project, so we'd have to get their permission if we want to release the site's code under a particular free license.

**Comment by KevinPayravi** [comment]
@aarohmankad & @rodrigoargumedo, we'd like to formally put the repository under a free software license. If either of you guys are open to releasing the code you've contributed to this repository under a free license, please comment :) I'm fine with either MIT or GPL V3.

**Comment by paked** [comment]
I'd personally prefer GPL, but MIT is fine too.

**Comment by rodrigoargumedo** [comment]
MIT license should be fine for me.

**Comment by rodrigoargumedo** [comment]
You can use the most common MIT License to deal majority of the legal stuff?
On Jul 16, 2015 8:51 PM, Kevin Payravi <notifications@github.com> wrote:Ah, yea, this is something I wish I had done at the beginning. Problem is that other users have already contributed to the project, so we'd have to get their permission if we want to release the site's code under a particular free license.

**Comment by aarohmankad** [comment]
I'm fine with whatever license. I've used both MIT and GPL in the past.

**Comment by KevinPayravi** [comment]
As we're all good with MIT, I've updated the documentation and site with the license. Thanks guys!

**Comment by paked** [comment]
Yay!
