### ISSUE TITLE
IOTA Hackathon

### ISSUE THREAD

**Issue by deerdear** [Hackalist/Hackalist.github.io#362]
**When**
17 - 18 November 2017

**Where**
Gdansk, Poland

**What**
[Info here](https://www.meetup.com/preview/Data-Science-Gdansk/events/244244467)
WHAT’S THE IOTA HACKATHON ALL ABOUT?

• Developing services or products for the internet of things

• Gaining experience with IOTA’s blockless ledger system for cutting-edge machine to machine transactions

• Keynote speeches by key players in the industry

• Networking, fun, free food and friendly competition

**How to attend**
Register over Meetup.com: [Here](https://www.meetup.com/preview/Data-Science-Gdansk/events/244244467)

**Comment by rodrigoargumedo** [comment]
Closing this pull request because this event is now past and I apologize for the convenience that may have caused.
