### ISSUE TITLE
Legal Aid Hackathon

### ISSUE THREAD

**Issue by josephjoseph99** [Hackalist/Hackalist.github.io#364]
Legal Aid Hackathon to develop technologies to improve access to justice.

Date: Tuesday, January 9, 2018

Location: JW Marriott New Orleans, 614 Canal Street, New Orleans, LA

Website: https://drupal.openadvocate.org/node/33

Registration: https://fjtc.typeform.com/to/cMBYnD

Questions? Contact Joseph Schieffer at joseph@floridajusticetechnologycenter.org

**Comment by rodrigoargumedo** [comment]
Closing this pull request because this event is now past and I apologize for the convenience that may have caused.
