### ISSUE TITLE
Barrick Gold Innovation Hackathon

### ISSUE THREAD

**Issue by PRyan234** [Hackalist/Hackalist.github.io#366]
London, UK. 24th-26th November. 
£12,500 in prizes and Google Startup credits.
Leading mentors, judges and speakers. 
Three challenges, Blockchainn, Robotics, symbiotic dev 
register here and learn more [https://www.eventbrite.co.uk/e/innovation-hackathon-london-registration-39257445075]

**Comment by rodrigoargumedo** [comment]
Closing because this event is now past event.
