### ISSUE TITLE
StarterHacks2018

### ISSUE THREAD

**Issue by shreyasubbu** [Hackalist/Hackalist.github.io#373]
March 3-4, 2018
Hackathon directed towards first-time hackers at the University of Waterloo, in Waterloo, ON. 
Open to high school and university/college students. 
Events Page: [https://www.facebook.com/events/145871806207338/](url)
Website: https://starterhacks.ca/

**Comment by jrsai** [comment]
{
      "title": "StarterHacks",
      "url": "https://starterhacks.ca/",
      "startDate": "March 3",
      "endDate": "March 4",
      "year": "2018",
      "city": "Waterloo, ON, Canada",
      "host": "University of Waterloo",
      "length": "24",
      "size": "500",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/events/145871806207338/",
      "twitterURL": "https://twitter.com/starterhacks",
      "googlePlusURL": "",
      "notes": ""
    }
