### ISSUE TITLE
Add this HACKATHON

### ISSUE THREAD

**Issue by arc113** [Hackalist/Hackalist.github.io#378]
{
      "title": "Hack in the North",
      "url": "https://www.hackinthenorth.com/",
      "startDate": "January 16",
      "endDate": "January 18",
      "year": "201",
      "city": "Allahabad, Uttar Pradesh, India",
      "host": "IIITA",
      "length": "36",
      "size": "500+",
      "travel": "yes",
      "prize": "yes",
      "highSchoolers": "unknown",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/HackInTheNorth/",
      "twitterURL": "https://twitter.com/besthackathon",
      "googlePlusURL": "",
      "notes": ""
    }

**Comment by rodrigoargumedo** [comment]
Closing because the event is now past. Thanks for contributing!
