### ISSUE TITLE
Hack UX, Designing the Future of Messaging & Bot

### ISSUE THREAD

**Issue by MUXL** [Hackalist/Hackalist.github.io#387]
This Design hackathon is on communications design in an enhanced messaging environment. This Hackathon is open to all across Product, Design, Dev etc. You will have the opportunity to prototype your ideas using the Oracle Platform with Oracle Intelligent Bots. You won’t need be technical to use the platform as you will be designing & creating prototypes but familiarity with mark-up languages and hooking-up APIs etc will also be useful in this Hackathon

https://mobileuxlondon.com/events/hackux_orange_oracle_enhanced_messaging/

**Comment by rodrigoargumedo** [comment]
Hey @MUXL, would you mind if you send us your JSON form of the hackathon listing? (See example below)

```json
{
      "title": "Best Hackathon",
      "url": "http://besthackathon.com/",
      "startDate": "January 20",
      "endDate": "January 21",
      "year": "2016",
      "city": "New York, NY, United States",
      "host": "Best University",
      "length": "36",
      "size": "200",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "unknown",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/besthackathon",
      "twitterURL": "https://twitter.com/besthackathon",
      "googlePlusURL": "",
      "notes": ""
    }```

**Comment by jrsai** [comment]
{
      "title": "Hack UX",
      "url": "https://mobileuxlondon.com/events/hackux_orange_oracle_enhanced_messaging/",
      "startDate": "April 27",
      "endDate": "April 28",
      "year": "2018",
      "city": "London, UK, England",
      "host": "Oracle City Office",
      "length": "18",
      "size": "50",
      "travel": "unknown",
      "prize": "yes",
      "highSchoolers": "unknown",
      "cost": "€24",
      "facebookURL": "https://www.facebook.com/events/183105302303551/",
      "twitterURL": "https://twitter.com/mobileuxlondon",
      "googlePlusURL": "",
      "notes": ""
    }
