### ISSUE TITLE
Hackathon ShowMeData 14-15 April 2018 Warsaw, Poland

### ISSUE THREAD

**Issue by Statistics-Poland** [Hackalist/Hackalist.github.io#391]
Dear Sir or Madam,

I would like to ask you for adding to your base information about our hackathon;

{
"title": "ShowMeData Hackathon GUS",
"url": "https://hackathon.stat.gov.pl/",
"startDate": "April 14",
"endDate": "April 15",
"year": "2018",
"city": "Warsaw, Poland",
"host": "Statistics Poland / Główny Urząd Statystyczny",
"length": "36",
"size": "60",
"travel": "no",
"prize": "yes",
"highSchoolers": "no",
"cost": "free",
"facebookURL": "https://www.facebook.com/events/170932660370933/?acontext=%7B%22ref%22%3A%223%22%2C%22ref_newsfeed_story_type%22%3A%22regular%22%2C%22feed_story_type%22%3A%2222%22%2C%22action_history%22%3A%22null%22%7D",
"twitterURL": "https://twitter.com/hashtag/ShowMeData?src=hash",
"googlePlusURL": "",
"notes": "The Statistics Poland organizes a hackathon for students and graduates of IT or related fields. The competition task is to create a prototype of a mobile application with the function of augmented reality, containing elements of e-learning and gamification. The prototype has to make use of public statistical data available in the Eurostat databases (European Statistical Office) by means of API. We expect a user-friendly application with intuitive interface and attractive graphics address at teenagers aged 12-15. We are waiting for teams of 2 to 4 people. All prototypes crated during the hackathon will be evaluated by Jury and the winners will receive valuable prizes for their programs – the main prize is PLN 20,000 (equivalent of USD 5871 or EUR 4768). 
We speak English, but our hackathon website, registration form (https://rejestracja.stat.gov.pl/hackathon), rules (https://hackathon.stat.gov.pl/regulamin), contract template etc. are available in Polish only. Feel free to translate it (e.g. by Google Translate) and if you have any question please send us e-mail to: hackathon@stat.gov.pl or phone us: +48 22 449 41 45 (Mo-Fr 8:15 to 16:15 CET)."
}

If you have any questions please send us e-mail to: hackathon@stat.gov.pl or phone us: +48 22 449 41 45 (Mo-Fr 8:15 to 16:15 CET)

Yours faitfully,
Tomasz Pudłowski
Chief specialist

 
Statistics Poland
Information Division
Aleja Niepodległości 208, 00-925 Warszawa
tel. +48 22 449 40 10
t.pudlowski@stat.gov.pl
stat.gov.pl

**Comment by rodrigoargumedo** [comment]
I added this into the directory. Thanks for the information!

**Comment by Statistics-Poland** [comment]
Thank you very much.

I cant't see April here: http://www.hackalist.org/ - how to see our hackathon?

Best regards,
Tomasz Pudłowski

**Comment by rodrigoargumedo** [comment]
I'm reopening this issue to diagnose the problem.

**Comment by rodrigoargumedo** [comment]
It should be fixed and will appear on the next refresh on your end.
