### ISSUE TITLE
Deprecate googlePlusURL

### ISSUE THREAD

**Issue by rodrigoargumedo** [Hackalist/Hackalist.github.io#392]
As Google moves on with their products, I would want to deprecate the googlePlusURL because no one really uses that anymore (with the exception of a few who use it often). I would like to provide input on this. @Hackalist/team-hackalist-github-io

**Comment by jrsai** [comment]
I agree! I recommend swapping it out for Instagram...a lot of people have started using that platform at Hackathons

**Comment by paked** [comment]
I don't think it's worth deprecating it until we absolutely have to (ie. Google actually shutting down Plus) -- it's not like it's taking up large amounts of resources by being an option.

However, maybe it is worth having a discussion about adding in some new links. Instagram seems like a good candidate.

**Comment by rodrigoargumedo** [comment]
@Hackalist/team-hackalist-github-io Reopening the issue because Google announced Google+ is shutting down the service. [Source](https://www.theverge.com/2018/10/8/17951890/google-plus-shut-down-security-api-change-gmail-android)

**Comment by RyanPisuena** [comment]
Issue fixed with #437
