### ISSUE TITLE
Hackathon - Addressing the UK Skills Shortage

### ISSUE THREAD

**Issue by MUXL** [Hackalist/Hackalist.github.io#394]
We are looking for participants to attend a free Hackathon run by EEF - The Manufacturers' Organisation. This is a fantastic opportunity to meet with industry leaders from some of Britain’s most innovative companies, such as BMW, Rolls Royce, Siemens, Estee Lauder and many more.

This Hackathon will look at UK’s current crisis around the future of manufacturing and the skills shortage in the UK. the EEF is joining forces with some of the greatest minds from leading trade, manufacturing, media and education sectors.

The event is free to attend and lunch and refreshments will be provided. This takes place at Huckletree, Finsbury Sq from 10am until 4pm on Thursday 19th April, will look at how we entice tomorrow's engineers to embark on a career in manufacturing and engineering.

**Comment by rodrigoargumedo** [comment]
Closing due to the event is now past. However, thanks for making this hackathon submission. Feel free to make more submissions and we'll happily take future request as soon as possible.
