### ISSUE TITLE
ActInSpace 2018 - International Space Innovation Hackathon Coming to the US

### ISSUE THREAD

**Issue by maliotfilozof** [Hackalist/Hackalist.github.io#400]
![cover](https://user-images.githubusercontent.com/38497861/38932587-f6f1d6ac-4316-11e8-8acc-e64588b75d22.png)
### Calling all challenge enthusiasts: It’s time to unleash your entrepreneurial potential! For the first time ever, we are bringing [ActInSpace](https://actinspace.org) across 15 locations in the United States. Come and join us in this remarkable experience!

Designed for students but open to everyone, ActInSpace aims to cultivate entrepreneurship, encourage start-up creation and promote the use of space technologies and space acquired data to change citizen’s lives, boost employment and protect our planet.
 
Discover the potential of space-based technologies and transform your idea into a real-life business! 
ActInSpace is a unique opportunity for people worldwide to work on one of the contests’ many challenges and use patents and technologies made available by Airbus, CNES (French Space Research Agency) & ESA (European Space Agency) to create game-changing solutions. The challenges are based on high-level technologies, which nevertheless are easy to re-use as they have been selected due to their potential for commercial applications. 
 
Don’t worry, you don’t have to be an expert to be a part of ActInSpace. 
Join forces with people who share your passion and together, under the guidance of experienced mentors who can fill in the gaps, you’ll be able to overcome any obstacle in your way!
 
So how does it work?
For 24 hours, your team will be imagining and designing innovative services and products derived from space technologies and space acquired data. With the advice of business mentors and technical experts, you will be working on real-life challenges and coming up with creative solutions that find everyday uses (for space technologies or data). 
 
And that’s just the beginning! 
The winning teams will proceed to the global finals to present their project to an international jury of experts on technology transfer and business development.
All teams with promising projects will go on to receive guidance from ESA’s Business Incubation Centers and partner incubators to accelerate their project and turn their idea into a real company.  So get ready to be coached, advised and encouraged by top technical and business experts around the clock transforming your idea into a winning business concept.
 
What makes this experience so compelling is that it is first and foremost meant for start-up teams who will continue to develop commercial solutions based on existing patents from ESA or any of the corporate partners of AIS, for example Airbus who will financially support the start-up company. The best start-ups receive a position in one of the 16 ESA space tech incubators located in the countries who are members of the agency. 
Aside from financial support for your start-up, as a winner you have the opportunity receive:
• a ticket for the weightlessness experience
• pilot training on Airbus A320 simulator and a visit of Airbus Defense & Space’s satellite integration room and 3D facilities
• a voucher of 100k€ of satellite derived data
 
 
By taking part in ActInSpace, you’ll be taking part in a truly international event bringing together entrepreneurs, students, job seekers, developers and creatives worldwide from over 70 cities across 5 continents, all working towards improving our lives on and off Earth.

**Comment by rodrigoargumedo** [comment]
Closing this issue due to the event is now past. However, thanks for your contribution for submission of this hackathon!
