### ISSUE TITLE
Add A Hackathon

### ISSUE THREAD

**Issue by jessee3em** [Hackalist/Hackalist.github.io#401]
![unknown-1](https://user-images.githubusercontent.com/38516890/38970066-61b96578-4361-11e8-877e-fbafc05a01e8.png)

Delaware's first blockchain hackathon

 BlockHack, a 24 hour Blockchain Hackathon happening at the University of Delaware on May 5-6th. www.blockhack.de

This event will have sponsor companies like Ark.io hosting workshops and prizes for developing on their platforms, and we'd love to have you join us! Also checkout our pre-hackathon workshops on our YouTube channel.

Let tbrunson@udel.edu know if you have any questions, and feel free to share this event with any one you feel would be interested.

**Comment by jessee3em** [comment]
$3500 in prizes

**Comment by jessee3em** [comment]
Blockchain Hackathon

**Comment by rodrigoargumedo** [comment]
Closing due to the event is now past.
