### ISSUE TITLE
Please Add - HackHLTH 

### ISSUE THREAD

**Issue by Kscheven** [Hackalist/Hackalist.github.io#402]
Site: https://hlth.co/hackhlth/

![hackhlth_logo_3-01-1024x156](https://user-images.githubusercontent.com/24257724/39206481-6647fde8-47b2-11e8-96ab-5eef1178d048.png)

Date: May 4-6

Location: Las Vegas

Info: Premier healthcare hackathon with over 140K in prizes and travel stipends available

**Comment by rodrigoargumedo** [comment]
Closing due to the event now past.
