### ISSUE TITLE
Add Women.Tech.Fab(WTF) Hackathon

### ISSUE THREAD

**Issue by cb-sankari** [Hackalist/Hackalist.github.io#408]
## Women.Tech.Fab. (WTF)
June 23 - June 24 in Chennai, India

Hosted by _Chargebee Technologies_ for 36 hours.

Capacity: 100

Cost: Free

WTF is a hackathon run by women, for women, at Chargebee. We want to build the right platform to bring together the best minds in tech who can spot, solve, and spearhead like a boss.

Travel reimbursement not offered
Prizes offered! 
High schoolers not accepted

**Comment by rodrigoargumedo** [comment]
It's now added to the listings! Thanks for your contribution!
