### ISSUE TITLE
Add github star/watch buttons

### ISSUE THREAD

**Issue by paked** [Hackalist/Hackalist.github.io#42]
Found these [neat github buttons](https://ghbtns.com/). I think we should try and get some use out of them, they are a bit nicer than the normal ~~bootstrap~~ skeleton button we have right now. Although, because they have different purposes maybe we should have them co-exist... Except I have no idea where we would put them.

**Comment by KevinPayravi** [comment]
*Skeleton, but yep! I was hoping to change our buttons to something more
unique at some point. I'd also love to bring the star and/or watch buttons
back; I believe I used to have them, but removed them for a reason I forgot.

On Wed, Jul 22, 2015, 7:20 PM Harrison Shoebridge <notifications@github.com>
wrote:

> Found these neat github buttons <https://ghbtns.com/>. I think we should
> try and get some use out of them, they are a bit nicer than the normal
> bootstrap button we have right now. Although, because they have different
> purposes maybe we should have them co-exist... Except I have no idea where
> we would put them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hackalist/Hackalist.github.io/issues/42>.
>
-- 
Kevin Payravi
W: http://www.kevinpayravi.com
P: (330) 554 - 3397

**Comment by paked** [comment]
Any idea where they used to be?
