### ISSUE TITLE
Add WhatTheHack Belgium

### ISSUE THREAD

**Issue by tobiascornille** [Hackalist/Hackalist.github.io#443]
{
      "title": "WhatTheHack Belgium 2019",
      "url": "https://whatthehack.be/",
      "startDate": "March 1",
      "endDate": "March 2",
      "year": "2019",
      "city": "Leuven, Belgium",
      "host": "Academics For Technology and Tobania",
      "length": "24",
      "size": "250",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "no",
      "cost":"free",
      "facebookURL": "https://www.facebook.com/events/1616242802008659/",
      "twitterURL": "",
      "googlePlusURL": "",
      "notes": ""
    }

**Comment by Yashvendra** [comment]
I have added it today!

**Comment by rodrigoargumedo** [comment]
Closing because it is now merged into the master branch from #447.
