### ISSUE TITLE
Add Master the Mainframe

### ISSUE THREAD

**Issue by Kscheven** [Hackalist/Hackalist.github.io#448]
{
"title": "Master the Mainframe 2018",
"url": "https://masterthemainframe.com/",
"endDate": "December 31",
"year": "2018",
"city": "Global Event",
"host": "IBM and AngelHack",
"travel": "no",
"prize": "yes",
"highSchoolers": "yes",
"cost":"free",
"facebookURL": "",
"twitterURL": "",
"googlePlusURL": "",
"notes": ""
}

**Comment by rodrigoargumedo** [comment]
Closing because it is now past.
