### ISSUE TITLE
Month buttons not properly centering

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#45]
Noticed the month nav buttons aren't properly centered, at least in Chrome:

![image](https://cloud.githubusercontent.com/assets/7636606/8867649/2a8a3004-319a-11e5-8793-cdc04d949266.png)

Don't have time tonight to look at unfortunately.

**Comment by paked** [comment]
So I've tried to look fix this, however it just does not make any sense to me. I think someone more intimate with the CSS codebase should take it... I think the problem may be a bit deeper than a misaligned div.

**Comment by KevinPayravi** [comment]
Skeleton and other boilerplates can definitely get funky like that :/ Haven't had a chance to mess around yet myself.

**Comment by paked** [comment]
We really need to fix this :)

**Comment by rodrigoargumedo** [comment]
I will take a stab at this bug now and if I find a solution, then I will throw a pull request to close this issue.

**Comment by paked** [comment]
Awesome!

**Comment by rodrigoargumedo** [comment]
I have been fiddling around with the code today and what do you think of this [fix](https://hackalist-rodrigoargumedo.c9.io/)?

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Thanks for looking into it! Unfortunately it's still misaligned on my end, the buttons just appear smaller :(

**Comment by rodrigoargumedo** [comment]
I am currently figuring out what to align this property correctly. I think these StackOverflow answers some Angular specific alignment [here](http://stackoverflow.com/questions/14703517/angular-js-set-element-height-on-page-load) and [here].

**Comment by KevinPayravi** [comment]
So I did a fix with [this commit](https://github.com/Hackalist/Hackalist.github.io/commit/db12c95067e86c7e6dce2f5fb7a0353ef88be466). I replaced "four columns" with "offset-by-one three columns", and that seems to have done the trick.

![image](https://cloud.githubusercontent.com/assets/7636606/9371025/32379b98-46a3-11e5-8818-97dcbdaba4e5.png)

There's probably a better way to go about this (I don't like the large amount of space between buttons, for example), but this should do for now I think :)

**Comment by paked** [comment]
Yep, LGTM.

**Comment by KevinPayravi** [comment]
@paked Thanks for confirming. I'll close this issue unless something comes up again.
