### ISSUE TITLE
Possibilities of additional URLs

### ISSUE THREAD

**Issue by mikini** [Hackalist/Hackalist.github.io#450]
How about making the url mechanism a little more flexible.

For the event of #449 I could have added urls for both the [host venue](https://bloxhub.org/event/aec-hackathon/) and the [ticket site](https://www.eventbrite.com/e/aec-hackathon-60-copenhagen-tickets-51738121113).

Maybe just have an url object as an array of arrays or objects with an identifier and an url. Then handle the case of urls that is to be prominently displayed (main site, tw, fb) special and list additional items somewhere convenient as nice links.

Example using arrays:
```
"urls": [
  ["main", "https://aechackathon.com/copenhagen/"],
  ["twitter", "http://twitter.com/fakeevent"],
  ["facebook", "http://facebook.com/events/fake"],
  ["eventbrite","https://www.eventbrite.com/e/aec-hackathon-60-copenhagen-tickets-51738121113"],
  ["host","https://bloxhub.org/event/aec-hackathon/"]
],
```

**Comment by rodrigoargumedo** [comment]
@Hackalist/team-hackalist-github-io bump.
