### ISSUE TITLE
Request to add Pragyan Hackathon

### ISSUE THREAD

**Issue by Thomasm18** [Hackalist/Hackalist.github.io#494]
{
      "title": "Pragyan Hackathon",
      "url": "https://pragyanhackathon.hackerearth.com//",
      "startDate": "December 21",
      "endDate": "December 22",
      "year": "2019",
      "city": "Bangalore",
      "host": "NIT Trichy",
      "length": "30",
      "size": "unknown",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "INR 500",
      "facebookURL": "https://www.facebook.com/pragyan.nitt/",
      "twitterURL": "https://www.facebook.com/pragyan.nitt/",
      "googlePlusURL": "",
      "notes": ""
    }

**Comment by rodrigoargumedo** [comment]
Thanks, @Thomasm18!
