### ISSUE TITLE
Remove hackathons from previous month

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#52]
@paked What do you think about removing hackathons from the previous month (in this case, August)? It's nice to have, but with the long list of hackathons, it's probably best to shorten the list.

**Comment by rodrigoargumedo** [comment]
@KevinPayravi I think to this very point, I would highly suggest you remove the August hackathons. It keeps it organized IMHO.

**Comment by paked** [comment]
I thought we already did this?

**Comment by paked** [comment]
I'd be happy to take a look, but I'm about to get on a flight from SFO->SYD... Thus it won't be done for 20 hours or so.

**Comment by KevinPayravi** [comment]
I tried to do it an hour or two ago, but screwed up...I'm not savvy. If you (or anyone else) can look at it later that'd be great!
