### ISSUE TITLE
RestartIndia Hackathon

### ISSUE THREAD

**Issue by Swags1430** [Hackalist/Hackalist.github.io#522]
RestartIndia Online Hackathon 2020 is an initiative for building solutions around problems that arose due to the ongoing COVID- 19 pandemic.

RestartIndia Hackathon invites techies from India’s student and professionals community to adopt the Think→Ideate→Code→Build→Deploy framework on their solutions to fight the problems running rampant.

Hackathon Schedule - 10th June to 14th June

[RestartIndia Hackathon](https://restartindia.org/)

**Comment by rodrigoargumedo** [comment]
Can you add the information into a nice and tidy JSON format [from the readme](https://github.com/Hackalist/Hackalist.github.io#listing-example)?

**Comment by Swags1430** [comment]
Hi Rodrigo,
Please find requested details

{
      "title": "RestartIndia Hackathon",
      "url": "http://restartindia.org/",
      "startDate": "June 12",
      "endDate": "June 14",
      "year": "2020",
      "city": "India,",
      "host": "RestartIndia.org",
      "length": "48",
      "size": "250",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/RestartIndiaorg",
      "twitterURL": "https://twitter.com/restartIndiaorg",
      "googlePlusURL": "",
      "notes": ""
    }
