### ISSUE TITLE
Paid Vs. Unpaid

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#57]
When I created Hackalist, my goal was for it to be a directory of hackathons accessible to anyone. One of the criteria I had in mind is that hackathons must be free. However, there are some great hackathons out there that do have an entry fee (usually small: $10 - $25).

I'm looking for input on whether or not we want to include hackathons that have an entry free. If so, we could also make a new API field on whether or not there's a cost to get in.

Pining potentially interested people:
@aarohmankad @paked @rodrigoargumedo

**Comment by rodrigoargumedo** [comment]
That is completely up to you to bring those features alive. I would normally say yes to this. We, as users, would want to know is the entry fee for the specific Hackathon in order before attending the event. (i.e. @CodeDay).


/cc @tjhorner



From: Kevin Payravi

Sent: Saturday, October 3, 10:42 AM

Subject: [Hackalist.github.io] Paid Vs. Unpaid (#57)

To: Hackalist/Hackalist.github.io

Cc: Rodrigo Argumedo



When I created Hackalist, my goal was for it to be a directory of hackathons accessible to anyone. One of the criteria I had in mind is that hackathons must be free. However, there are some great hackathons out there that do have an entry fee (usually small: $10 - $25).


I'm looking for input on whether or not we want to include hackathons that have an entry free. If so, we could also make a new API field on whether or not there's a cost to get in.


Pining potentially interested people:

@aarohmankad @paked @rodrigoargumedo

**Comment by paked** [comment]
@KevinPayravi I believe this choice is up to you :)

**Comment by tjhorner** [comment]
Include hackathons with an entry fee, put a little note saying that there is one.

**Comment by paked** [comment]
:+1: for @tjhorner's suggestion. I don't personally see an issue with paid hackathons being in the database, as long as they have a note saying they require an entry fee.

**Comment by KevinPayravi** [comment]
Sounds good to me guys, thanks for the input!

I think the best way to move forward would be to add a "cost" field to the API, and add a toggle for hackathons that have an entry fee. We can replace the "prize" toggle with that, since practically every hackathon has prizes of some sort.

**Comment by paked** [comment]
OK. Sounds good to me.

**Comment by KevinPayravi** [comment]
Closing. Consensus is to include paid hackathons; will add parameters to JSON files in future.
