### ISSUE TITLE
[listing-request] Add Startup Weekend Global

### ISSUE THREAD

**Issue by Liljasmine92** [Hackalist/Hackalist.github.io#602]
Please paste the following information into the following text to list your hackathon:

```
    {
      "title": "Startup Weekend Global",
      "url": "https://www.eventbrite.com/e/startup-weekend-global-2022-tickets-420221532917",
      "startDate": "9 December 2022",
      "endDate": "4 March 2023",
      "year": "2023",
      "city": "All",
      "host": "Techstars",
      "length": "NA",
      "size": "2000",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "yes",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/startupweekendsingapore/",
      "twitterURL": "https://twitter.com/sw_singapore",
      "notes": "Join the largest, wildest and most exciting hackathon! This year, we are delving into the exciting theme of Web3, so join us on this incredible journey today. "
    }
```

**Comment by rodrigoargumedo** [comment]
> Hey! I realised that the information I filled out nay have been deleted.. is this sufficient?
> 
> > Please paste the following information into the following text to list your hackathon:
> > ```
> >     {
> >       "title": "Startup Weekend Global 2022 Web3 Edition",
> >       "url": "https://startupweekendglobal.com/",
> >       "startDate": "December 9 2022",
> >       "endDate": "March 2 2023",
> >       "year": "-",
> >       "city": "online",
> >       "host": "Techstars Startup Weekend",
> >       "length": "86 days",
> >       "size": "2000 tickets",
> >       "travel": "no",
> >       "prize": "yes",
> >       "highSchoolers": "yes",
> >       "cost": "free",
> >       "facebookURL": https://www.facebook.com/startupweekendsingapore/ "",
> >       "twitterURL": "https://twitter.com/sw_singapore",
> >       "notes": "sign up here: https://www.eventbrite.com/e/startup-weekend-global-2022-tickets-420221532917"
> > ```

I think that is sufficient, but let me get that listing into the site.
