### ISSUE TITLE
[listing-request] Add [Your Hackathon Name]

### ISSUE THREAD

**Issue by apollo-24** [Hackalist/Hackalist.github.io#604]
Please paste the following information into the following text to list your hackathon:

```
    {
      "title": "Your Hackathon Name",
      "url": "http://hackathon.com/",
      "startDate": "January 20",
      "endDate": "January 21",
      "year": "2016",
      "city": "New York, NY, United States",
      "host": "XYZ University",
      "length": "36",
      "size": "200",
      "travel": "no",
      "prize": "yes",
      "highSchoolers": "unknown",
      "cost": "free",
      "facebookURL": "https://www.facebook.com/yourhackathonname",
      "twitterURL": "https://twitter.com/yourhackathonname",
      "notes": ""
    }
```

Admin note: deleted personal info for exposure prevention.

**Comment by rodrigoargumedo** [comment]
Hi there, is there more information that I can help you provide your listing? I can't put example information until provided correct information.

**Comment by Liljasmine92** [comment]
Hey! I realised that the information I filled out nay have been deleted.. is this sufficient?

> Please paste the following information into the following text to list your hackathon:
> 
> ```
>     {
>       "title": "Startup Weekend Global 2022 Web3 Edition",
>       "url": "https://startupweekendglobal.com/",
>       "startDate": "December 9 2022",
>       "endDate": "March 2 2023",
>       "year": "-",
>       "city": "online",
>       "host": "Techstars Startup Weekend",
>       "length": "86 days",
>       "size": "2000 tickets",
>       "travel": "no",
>       "prize": "yes",
>       "highSchoolers": "yes",
>       "cost": "free",
>       "facebookURL": https://www.facebook.com/startupweekendsingapore/ "",
>       "twitterURL": "https://twitter.com/sw_singapore",
>       "notes": ""

**Comment by apollo-24** [comment]
Snapchat-kayla_tuner22 
Facebook-Kayla Turner 
Name-Kayla M Tuner 
Age 33
Moses Lake, Wa
Number-(719) 640-9542
Twitter-https://twitter.com/kaylatuner869?s=21&t=XQeiB9oQm2jdKF4CckHe6A


https://t.snapchat.com/LtalkR12
![image](https://user-images.githubusercontent.com/121984564/219935273-0a284c41-ff6f-448b-9d43-106aa8fadcb0.png)

**Comment by apollo-24** [comment]
Nice 😎
