### ISSUE TITLE
Can anyone translate the README.md to english?

### ISSUE THREAD

**Issue by apollo-24** [Hackalist/Hackalist.github.io#605]
Can anyone translate the README.md to english?

_Originally posted by @dev-shah-2204 in https://github.com/open-android/Android/issues/59_

**Comment by rodrigoargumedo** [comment]
Welcome to Hackalist! There are a lot of resources that can help you do this situation and it is searchable over the internet. I'm going to close and lock this issue as this issue as off-topic.
