### ISSUE TITLE
Hackathons in December

### ISSUE THREAD

**Issue by robgoyal** [Hackalist/Hackalist.github.io#66]
Can I add hackathons for the month of December? Didn't see a 12.json so I wasn't sure :o

**Comment by KevinPayravi** [comment]
Yes, definitely! Feel free to create it in the 2015 folder.

**Comment by KevinPayravi** [comment]
(And for that matter, if we have hackathons scheduled in 2016, that folder can be created too).

**Comment by robgoyal** [comment]
Yaaay, thank you! First time I've done pull requests on GitHub and I'm really enjoying it :D

**Comment by KevinPayravi** [comment]
No problem, and thanks for contributing! Glad you're enjoying it :) Hope you've signed up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/).
