### ISSUE TITLE
Hack Cambridge

### ISSUE THREAD

**Issue by wlyinan** [Hackalist/Hackalist.github.io#80]
Taking place from the 30th to the 31st of January 2016, the first large hackathon in Cambridge is bound to be a lot fun. 400 attendees will descend upon one of the world's oldest universities, some coming from as far as MIT, Singapore, and Egypt. Students from all over the world are welcome!

Like our Facebook page and apply now at http://www.hackcambridge.com/. Deadline for applications is 5 Dec.

P.S. This is a great excuse to visit the alma mater of Alan Turing and Borat.

**Comment by wlyinan** [comment]
Capacity: 400
Location: University of Cambridge, UK
Date: 30 Jan - 31 Jan (10am - 4pm, 24 hours)
Nominal Travel Reimbursement (would make a difference if taking a train/budget flight within EU, would not help much if travelling from beyond)

Prizes available

For University students or less than 1 year post-graduation people.

**Comment by paked** [comment]
Thank you for your contribution!
