### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#82]
Skeleton's great, but it's not really necessary for this project. I'll work on custom styling over Thanksgiving Break.

**Comment by paked** [comment]
Yes. SGTM.

**Comment by rodrigoargumedo** [comment]
@KevinPayravi You should do a mockup design, IMO. I can probably work on it when I get home by tonight.

**Comment by KevinPayravi** [comment]
Unfortunately didn't get a chance to get to this this weekend :(

@rodrigoargumedo Wasn't planning on anything that visually different; just wanted to remove dependency on Skeleton, which means styling buttons, font, etc. Feel free to come up with something if you wish!

**Comment by paked** [comment]
@rodrigoargumedo I think it would be cool to do a redesign. Maybe you should experiment with it?

**Comment by rodrigoargumedo** [comment]
@paked Absolutely.

Sent from Outlook




On Tue, Dec 1, 2015 at 11:33 AM -0800, "Harrison Shoebridge" <notifications@github.com> wrote:





@rodrigoargumedo I think it would be cool to do a redesign. Maybe you should experiment with it?

---

**Comment by rodrigoargumedo** [comment]
@KevinPayravi @paked What do you think of this new logo font? I am still working on the design of the page just yet and will share once I am happy with it. It feels light to me than the current one right now

![hackalist-logo-new](https://cloud.githubusercontent.com/assets/7613139/11921484/5c6b15ae-a74f-11e5-8590-a8034ef7decf.png)

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Thanks Rodrigo! Hmm...I still prefer the current logo, mostly because the new font isn't particularly unique.

**Comment by paked** [comment]
@rodrigoargumedo I personally think that we should keep the current logo, and focus on updating the site itself

**Comment by rodrigoargumedo** [comment]
After some thoughts, yeah, in favor of the current one.




On Sun, Dec 20, 2015 at 9:45 PM -0800, "Harrison Shoebridge" <notifications@github.com> wrote:





@rodrigoargumedo I personally think that we should keep the current logo, and focus on updating the site itself

---

**Comment by rodrigoargumedo** [comment]
After months of consideration and thoughts.. I may have the design we're probably seeking for all this time. Again, what is your opinion on this design?

![hackalist-page](https://cloud.githubusercontent.com/assets/7613139/11938363/00a16372-a7e0-11e5-84e3-0ef955c32431.jpg)

**Comment by rodrigoargumedo** [comment]
Still probably to tweak on square boxes' width, though.

**Comment by paked** [comment]
@rodrigoargumedo Could you fill out one of those boxes with an example hackathon for me?

**Comment by KevinPayravi** [comment]
I really like where this is going! Great design. Having more Hackathon
available at a glance, instead of having to scroll, is a necessity
Hackalist lacks.

Also curious on the source of the image at the top - do we have the right
to use it?

On Mon, Dec 21, 2015, 2:27 PM Harrison Shoebridge <notifications@github.com>
wrote:

> @rodrigoargumedo <https://github.com/rodrigoargumedo> Could you fill out
> one of those boxes with an example hackathon for me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hackalist/Hackalist.github.io/issues/82#issuecomment-166396580>
> .
>
-- 

Kevin Payravi
W: http://www.kevinpayravi.com
P: (330) 554 - 3397

**Comment by rodrigoargumedo** [comment]
@KevinPayravi Yes, per [Unsplash's creative commons public domain](https://unsplash.com/license).

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Great, just making sure. Nice job so far!

On Mon, Dec 21, 2015, 2:37 PM Rodrigo Argumedo <notifications@github.com>
wrote:

> @KevinPayravi <https://github.com/KevinPayravi> Yes, per Unsplash's
> creative commons public domain <https://unsplash.com/license>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hackalist/Hackalist.github.io/issues/82#issuecomment-166398824>
> .
>
-- 

Kevin Payravi
W: http://www.kevinpayravi.com
P: (330) 554 - 3397

**Comment by rodrigoargumedo** [comment]
For Angular code, we could create a controller that indexes and filters the keywords for hackathon names and all that. I like where this is going, too.

**Comment by rodrigoargumedo** [comment]
@paked Here you go:

![hackalist-page](https://cloud.githubusercontent.com/assets/7613139/11940873/05b5c2d4-a7f1-11e5-8347-a03e7f5ddff2.jpg)

**Comment by paked** [comment]
@rodrigoargumedo I could do that search quickly. Not much would need to be changed in the existing JS implementation

**Comment by rodrigoargumedo** [comment]
@paked Then, I am OK with it. @KevinPayravi Final words on this move?

**Comment by KevinPayravi** [comment]
All sounds great to me! Looking forward :)

**Comment by rodrigoargumedo** [comment]
@Hackalist/team-hackalist-github-io Then I will start working on it today until I exactly have what I want. Closing in a commit when done.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Woot! You rock. Could you upload the project as a branch when it's ready? That way we can review code, make any improvements, etc. before pushing it live.

**Comment by rodrigoargumedo** [comment]
@KevinPayravi Yes, I'll put up in my own [fork](https://github.com/rodrigoargumedo/Hackalist.github.io/tree/redesign).

**Comment by paked** [comment]
@rodrigoargumedo Yo have we got an update on how this is going? I'm personally happy to take over if need be.

I'm looking for an excuse to use http://materializecss.com on an already existing project, I could definitely create something similar looking to the design above. That said, it would look more Google-y because, you know, Material Design.

Either way, lets try and get a graphical update happening soon.

**Comment by rodrigoargumedo** [comment]
Feel free to take over the fork. I will give write access to it right now.

**Comment by KevinPayravi** [comment]
@paked Great idea, can't wait to see what you come up with :)

**Comment by rodrigoargumedo** [comment]
Consider that work in progress.

**Comment by rodrigoargumedo** [comment]
@paked It's your turn to shine! I granted you write access to the [fork](https://github.com/rodrigoargumedo/Hackalist.github.io/tree/redesign). So, let your adventures run wild!!

**Comment by paked** [comment]
OK. Status update.

So I've spent a bit of time hacking away and came up with this:

![screenshot 2016-02-29 14 55 38](https://cloud.githubusercontent.com/assets/8407370/13385423/940224d0-def4-11e5-8136-883173d6e171.png)

Next step before reintegrating the Angular logic is to fix up the colours and typography.

@rodrigoargumedo I'll look at bringing in your images soon after that.

**Comment by rodrigoargumedo** [comment]
That's good! Keep going, @paked!

**Comment by KevinPayravi** [comment]
Woohoo! Love it. Good stuff for a few hour's work.

**Comment by paked** [comment]
Sorry for the delay guys. I'm going to continue working on this ASAP, unfortunately my laptop died a few days ago which means I no longer have the capability to work on the bus :/

**Comment by KevinPayravi** [comment]
@paked No problem and no rush!

**Comment by rodrigoargumedo** [comment]
I am starting the redesign of the code right now with the [2.0](https://github.com/Hackalist/Hackalist.github.io/tree/2.0) branch. I will try my best to work everything from the issues that are still active and close them soon.
