### ISSUE TITLE
Add cost-to-attend as a field

### ISSUE THREAD

**Issue by KevinPayravi** [Hackalist/Hackalist.github.io#83]
As per [this discussion](https://github.com/Hackalist/Hackalist.github.io/issues/57), we'll track cost-to-attend (if there is one) for our listed hackathons. This should be implemented into the API, and previous hackathons should be updated to reflect this (all prior hackathons have been free-to-attend, unless specified in the notes).

**Comment by paked** [comment]
:+1:

**Comment by rodrigoargumedo** [comment]
Are we still doing this? I mean, @paked and I could do this together. Otherwise, I will remove this from the 2.0 milestone temporarily until further notice or action is taken.

**Comment by paked** [comment]
I think we could look at redesigning the API for version 2.

There are a few things I would like to see, but these are the most important IMO:

- Removing the redundant month information
- More specific information regarding the notes
- A keywords field

**Comment by paked** [comment]
In terms of actually making the transition, I could write a script to do this with a fair amount of ease.

**Comment by rodrigoargumedo** [comment]
I think this will be good transition. Keyword field is definitely important. What can we improve the `notes` field? IMO, we could rename it as `additional-notes` or something like that. What do you think?

**Comment by rodrigoargumedo** [comment]
I will also leave this to the community to decide on this transition as well.

**Comment by KevinPayravi** [comment]
I'd still like to include `cost` as a field, yep. I think it's an important note to mark on Hackalist, especially since we're seeing a good mix of free vs. non-free hackathons.

As @paked said, should be easy to script, especially since all our previously listed hackathons have been free, except for a couple which have been noted in the listings' notes.

**Comment by rodrigoargumedo** [comment]
Whenever think of the `cost` field, it should parse as something like `free` or `25` without the `$` sign into the arguments of the field. @paked will take a look at this once we have everything else tackled.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo I was thinking the same thing, but then I thought of the issue of international currency. We might see hackathons that work in `€`, for example. Trying to think of the solution to this...

- Converting prices to USD
- Having a separate field for the currency code or symbol (USD, EUR, etc.)
- Simply include the symbol in the field (e.g. `$25`)

Something to think about!

**Comment by rodrigoargumedo** [comment]
This is a great suggestion but I wonder if it will be a little too complex for the code in terms of readability? That also worries me a bit but I do not know if it will be a concern in the future.

**Comment by paked** [comment]
Why not just have that field as a string? Then people can use whatever currency they want.

I'd bias towards creating issues for all the new behaviours we want to add.

**Comment by rodrigoargumedo** [comment]
Good thinking. We should go with that approach instead.

**Comment by KevinPayravi** [comment]
@paked Sounds good, basically when I meant by "Simply include the symbol in the field". Definitely the simplest way to go about it.

**Comment by paked** [comment]
In the interest of sharing the work around @KevinPayravi @rodrigoargumedo would either of you be interested in taking this off my hands?

**Comment by KevinPayravi** [comment]
I'd be happy to - either sometime this week between two midterms, or this weekend when I'm free.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo If you find yourself bored and wanting to tackle this, feel free to take it :)

**Comment by rodrigoargumedo** [comment]
I will when I am done with my midterms this week.

**Comment by KevinPayravi** [comment]
I created a pull request that adds a cost field to all current listings: https://github.com/Hackalist/Hackalist.github.io/issues/83

All previous hackathons (as far as I could find) were listed for free except for one. If it all looks good, let's merge this in :)

**Comment by KevinPayravi** [comment]
Pull request merged; we now have a cost field :)

I'll create new issues for each of the other field recommendations made in this thread.
