### ISSUE TITLE
Turn the Hackalist account into an organisation

### ISSUE THREAD

**Issue by paked** [Hackalist/Hackalist.github.io#84]
Currently [hackalist](https://github.com/hackalist) is an individual, I feel it would be more representative to switch to an organisation... I believe this can be done at the press of a button, somewhere in setttings.

Sorry, I'm a bit OCPD about this meta stuff haha!

**Comment by rodrigoargumedo** [comment]
I told @KevinPayravi about this before. I'm 99.5% sure if he turning it into a github organisation. So, :+1: for this.

**Comment by rodrigoargumedo** [comment]
It's in Settings > Organisations > Turn hackalist into an organisation. @paked

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Sorry, I totally forgot about this! Definitely makes more sense to be an organization. I've made it so :)

Thank you both.

**Comment by rodrigoargumedo** [comment]
Now, with that in mind, you should give members specific access to repositories you own. As of right now, I and @paked may have limited access to the repo when after turning  the profile into an organization. However, it's off of a great start on this.

**Comment by paked** [comment]
@KevinPayravi Also you should change the username to just `Hackalist`.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Everything is the same rights-wise; paked has write access to the repo, as it was prior to the move. If you'd also like to be a collaborator on the project, just let me know :)

@paked Done, thanks!

**Comment by rodrigoargumedo** [comment]
I would love to be part of the contributor team.

**Comment by KevinPayravi** [comment]
@rodrigoargumedo Done, thanks! :)
