### ISSUE TITLE
remove month name used as a key

### ISSUE THREAD

**Issue by slimfire** [Hackalist/Hackalist.github.io#93]
On each json document, the name of the month is used as the object key and the data[hackathons] is stored as the value. I would recommend that json is presented as an array of objects[hackathons] as the user can easily find the month from on of the objects. Thanks !

**Comment by KevinPayravi** [comment]
Good point. Sounds like a bad design decision on my part, since each JSON file's month is clear from the file name itself. However, I worry about breaking any external applications that already use our JSON files; I'd rather not make any major changes unless necessary.

**Comment by slimfire** [comment]
Cool, that makes sense (y)

**Comment by KevinPayravi** [comment]
Closing for now, we can re-open in the future if a better solution is found.
