### ISSUE TITLE
Add HackDFW 

### ISSUE THREAD

**Issue by AustinCWells** [Hackalist/Hackalist.github.io#97]
4.16 4.17
Dallas, Texas 
HackDFW.com

**Comment by KevinPayravi** [comment]
Working on it.

**Comment by KevinPayravi** [comment]
Added, thanks Austin! (Commit: https://github.com/Hackalist/Hackalist.github.io/commit/8e586c81c763e956cab719711e2d822abfe2806f)

If you know how many students are attending, let me know or feel free to pull request it.
